# SPDX-FileCopyrightText: 2017 Stefano Babic <sbabic@denx.de>
#
# SPDX-License-Identifier: MIT

dist: focal
sudo: required

language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "wJ7iVkgyOeIY1AIZqeJ/kduIZ8ny9Bvi0QeNxkOOX2XkZ1bGrraTi8i/bQ0uk+uEp01G/XeBF8zB/7ntB51244sQfR2/ErixSKfYGFZRXBoIR/VJndst/azMSUjMc11TZwuWkiIJtmg4Aiz2jUmUvn0BTPwXWN4IKHp4IalYo5GJjEhbi/y94L/KraDlVJIJYT72gBKqxMN6Xqgrz0wB8sVF9jWkqmF2v/LVwDet9us5QRh8gfobK0fqnadQMQr+KImoi/tjK8JfHz6v2GSETi4kNsSidR/iQ3vZmZD2Zl16SsyxqoOAeUC0u8hN7yOCcMpFzXyvfzm5AayNyPOUcYojO0M14Yb5yYGPFTi7E6Ha5UO9aJIGZChfgWaOdbJ1ZsG7OOS9VAv5pdD7jpAQOmM/hxm6G7hCkB2asqMkM45UNCM8J3ipiBuq6cvTOTKY/0wp60kh96G02f9Eu9A9NQw3JrMNmcrObSPBHz6mUPA0hlze1Sj7OfylFBEjMtdlFheKbXsW013+C0gZPs/F+FxWppRjkBJYtdv9UKfZRuHAzaR1r4iv1DXTFBksOBjvp2XxNfe8GBRPFbDDjPbXL+8arsGnbNanlSd93r3uOTDLOjM8QN4tPeAtLpA0xv87YSJmbAsGpHneysaOGETMEoivTRXb0zLf4MmnMVsEqQY="

addons:
  coverity_scan:
    project:
      name: "sbabic/swupdate"
      description: Update agent for embedded linux
    notification_email: swupdate@googlegroups.com
    build_command_prepend: make all_handlers_defconfig
    build_command: make
    branch_pattern: coverity_scan

before_install:
  - ./ci/setup.sh
  - ./ci/install-src-deps.sh
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
  - ./ci/test-configs.sh
